import { DM_Sans } from 'next/font/google'
import { Providers } from './providers'
import './globals.css'

const dmSans = DM_Sans({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`dark text-foreground bg-chinese-black ${dmSans.className}`}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
